[global]
developmentMode = false
showWarningOnDirectExecution = false

[server]
port = 8501
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"
